#   docker compose -f docker-compose.yml -f docker-compose.gpu.yml up -d
services:
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    environment:
      ASR_MODEL: large-v3
      ASR_DEVICE: cuda
      ASR_QUANTIZATION: float16
      # MODEL_IDLE_TIMEOUT: 300
    healthcheck:
      start_period: 900s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
